# Generated by Django 5.1.1 on 2024-11-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('cita_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada cita. Este valor debe ser ·nico y permite distinguir cada cita de manera clara.', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_comment='Este campo almacena la fecha programada para la cita. Es importante para la gesti¾n de la agenda de la clÝnica y para que los clientes recuerden su cita.')),
                ('hora', models.CharField(db_comment='Este campo almacena la hora programada para la cita. Permite especificar el momento exacto en que la mascota serß atendida.', max_length=20)),
                ('motivo', models.CharField(blank=True, db_comment='Este campo almacena el motivo de la cita (por ejemplo, "Consulta general", "Vacunaci¾n", "Chequeo"). Ayuda al veterinario a prepararse para la atenci¾n de la mascota.', max_length=200, null=True)),
                ('estado', models.CharField(blank=True, db_comment='Este campo almacena el estado de la cita (por ejemplo, "Programada", "Cancelada", "Completada"). Esto permite gestionar el seguimiento de las citas y su estado actual.', max_length=40, null=True)),
            ],
            options={
                'db_table': 'citas',
                'db_table_comment': 'La tabla CITAS almacena informaci¾n sobre las citas programadas en la clÝnica veterinaria. Cada cita estß asociada con un cliente, un veterinario y una mascota especÝfica, lo que permite gestionar de manera efectiva las atenciones programadas.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinicas',
            fields=[
                ('clinica_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada clÝnica. Este valor debe ser ·nico y permite distinguir cada clÝnica de manera clara.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre de la clÝnica (por ejemplo, "Veterinaria San Francisco"). Es fundamental para identificar la clÝnica y facilitar su b·squeda.', max_length=50)),
                ('direccion', models.CharField(blank=True, db_comment='Este campo almacena la direcci¾n fÝsica de la clÝnica (por ejemplo, "Calle 123, San JosÚ"). Es importante para que los clientes puedan localizar la clÝnica.', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_comment='Este campo almacena el n·mero de telÚfono de la clÝnica. Permite a los clientes comunicarse con la clÝnica para realizar consultas o agendar citas.', max_length=20, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinicas',
                'db_table_comment': 'La tabla CLINICAS almacena informaci¾n sobre las clÝnicas veterinarias. Cada clÝnica tiene un identificador ·nico y puede incluir detalles como el nombre, direcci¾n, telÚfono y el usuario que la administra.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaMascotas',
            fields=[
                ('consulta_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada consulta. Este valor debe ser ·nico y permite distinguir cada consulta de manera clara.', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_comment='Este campo almacena la fecha en que se realiz¾ la consulta. Es importante para el seguimiento del historial mÚdico de la mascota y para saber cußndo se realiz¾ la atenci¾n.')),
                ('diagnostico', models.CharField(blank=True, db_comment='Este campo proporciona el diagn¾stico obtenido durante la consulta. Es esencial para el registro mÚdico y permite documentar la salud de la mascota y cualquier tratamiento recomendado.', max_length=100, null=True)),
            ],
            options={
                'db_table': 'consulta_mascotas',
                'db_table_comment': 'La tabla CONSULTA_MASCOTAS almacena informaci¾n sobre las consultas realizadas a las mascotas en la clÝnica veterinaria. Cada registro en esta tabla representa una consulta especÝfica, incluyendo detalles sobre la mascota, la fecha de la consulta y el diagn¾stico proporcionado.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('sintoma_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada sÝntoma, lo que permite distinguir claramente entre diferentes sÝntomas.', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_comment='Este campo proporciona una descripci¾n del sÝntoma. Es importante para ayudar a los veterinarios y al personal a reconocer y evaluar adecuadamente los sÝntomas que pueden presentar las mascotas.', max_length=100, null=True)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre del sÝntoma. Es fundamental para identificar rßpidamente el sÝntoma en la base de datos y en las interacciones con los clientes.', max_length=30)),
            ],
            options={
                'db_table': 'sintomas',
                'db_table_comment': 'La tabla SINTOMAS almacena informaci¾n sobre los sÝntomas que pueden presentar las mascotas. Cada registro representa un sÝntoma especÝfico, incluyendo su nombre y una descripci¾n que detalla las caracterÝsticas del sÝntoma.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('tratamiento_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada tratamiento. Este valor debe ser ·nico y permite distinguir cada tratamiento de manera clara.', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_comment='Este campo proporciona una descripci¾n detallada del tratamiento. Es importante para que los veterinarios y el personal de la clÝnica comprendan el prop¾sito y la naturaleza del tratamiento.', max_length=100, null=True)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre del tratamiento. Es fundamental para identificar rßpidamente el tratamiento en la base de datos y en las interacciones con los clientes.', max_length=30)),
            ],
            options={
                'db_table': 'tratamientos',
                'db_table_comment': 'La tabla TRATAMIENTOS almacena informaci¾n sobre los tratamientos que pueden ser administrados a las mascotas en la clÝnica veterinaria. Cada registro representa un tratamiento especÝfico, incluyendo su nombre y una descripci¾n detallada.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('vacuna_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada vacuna, lo que permite distinguir claramente entre diferentes vacunas.', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_comment='Este campo proporciona una descripci¾n de la vacuna. Es importante para informar a los veterinarios y al personal sobre el prop¾sito de la vacuna y cualquier detalle relevante sobre su administraci¾n.', max_length=100, null=True)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre de la vacuna. Es fundamental para identificar rßpidamente la vacuna en la base de datos y en las interacciones con los clientes.', max_length=30)),
            ],
            options={
                'db_table': 'vacunas',
                'db_table_comment': 'La tabla VACUNAS almacena informaci¾n sobre las vacunas disponibles para las mascotas en la clÝnica veterinaria. Cada registro representa una vacuna especÝfica, incluyendo su nombre y una descripci¾n que detalla su prop¾sito y uso.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbtoolsExecutionHistory',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('hash', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.TextField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('times', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dbtools$execution_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidad_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada especialidad. DeberÝa ser un valor ·nico que permite distinguir cada especialidad de manera clara.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre de la especialidad (por ejemplo, "DermatologÝa", "CirugÝa", "OdontologÝa"). Es un campo importante para identificar la especialidad de manera comprensible.', max_length=30)),
                ('descripcion', models.CharField(blank=True, db_comment='Este campo proporciona una descripci¾n detallada de la especialidad. Puede incluir informaci¾n sobre los servicios ofrecidos, condiciones tratadas o cualquier detalle relevante que ayude a entender mejor la especialidad.', max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidades',
                'db_table_comment': 'La tabla ESPECIALIDADES almacena informaci¾n sobre las especialidades disponibles en la clÝnica veterinaria. Cada especialidad tiene un identificador ·nico y puede incluir un nombre y una descripci¾n que brindan mßs detalles sobre la especialidad.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('factura_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada factura. Este valor debe ser ·nico y permite distinguir cada factura de manera clara.', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_comment='Este campo almacena la fecha en que se gener¾ la factura. Es importante para el registro y seguimiento de las transacciones realizadas.')),
                ('monto_total', models.FloatField(db_comment='Este campo almacena el monto total a pagar en la factura. Representa el costo de los servicios prestados y debe ser calculado correctamente.')),
                ('estado', models.CharField(db_comment='Este campo almacena el estado de la factura (por ejemplo, "Pagada", "Pendiente", "Cancelada"). Esto permite gestionar el seguimiento de los pagos y el estado actual de cada factura.', max_length=30)),
            ],
            options={
                'db_table': 'facturas',
                'db_table_comment': 'La tabla FACTURAS almacena informaci¾n sobre las facturas generadas por los servicios prestados en la clÝnica veterinaria. Cada factura estß asociada a una cita especÝfica y contiene detalles relevantes sobre el monto y el estado de la factura.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('servicio_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada servicio. Este valor debe ser ·nico y permite distinguir cada servicio de manera clara.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre del servicio (por ejemplo, "Consulta Veterinaria", "Vacunaci¾n"). Es importante para la identificaci¾n y presentaci¾n de los servicios a los clientes.', max_length=255)),
                ('descripcion', models.CharField(blank=True, db_comment='Este campo proporciona una descripci¾n detallada del servicio ofrecido. Ayuda a los clientes a entender mejor lo que incluye cada servicio y sus beneficios.', max_length=255, null=True)),
                ('costo', models.FloatField(db_comment='Este campo almacena el costo del servicio. Es esencial para el cßlculo de las facturas y para la gesti¾n financiera de la clÝnica.')),
                ('activo', models.BooleanField(blank=True, db_comment='Este campo almacena el valor booleano de si el servicio se encuentra activo, true para sÝ, esto se utiliza para la l¾gica de solicitar citas de para los usuarios clientes', null=True)),
                ('minutos_sesion', models.DecimalField(blank=True, db_comment='Este campo almacena el tiempo en minutos que dura cada sesi¾n', decimal_places=2, max_digits=10, null=True)),
                ('numero_sesiones', models.DecimalField(blank=True, db_comment='Este campo almacena el n·mero de sesiones necesarias para completar un tratamiento, es 1 por defecto lo que significa que en una sola sesi¾n se completa', decimal_places=2, max_digits=10, null=True)),
                ('dir_imagen', models.CharField(blank=True, db_comment='Este campo almacena la direcci¾n en la que se encuentra la imagen en el directorio del servidor, es nulo por defecto, lo que significa que no tiene una imagen asociada', max_length=255, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'db_table_comment': 'La tabla SERVICIOS almacena informaci¾n sobre los diferentes servicios que ofrece la clÝnica veterinaria. Cada servicio tiene un identificador ·nico y se asocia con un costo especÝfico, lo que permite a la clÝnica gestionar su catßlogo de servicios de manera efectiva.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosVeterinarios',
            fields=[
                ('horario_id', models.FloatField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('activo', models.FloatField()),
            ],
            options={
                'db_table': 'horarios_veterinarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('mascota_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada mascota. Este valor debe ser ·nico y permite distinguir cada mascota de manera clara.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_comment='Este campo es una llave forßnea que almacena el n·mero de cÚdula del cliente. Es ·til para identificar al cliente de manera oficial y asegurar que la mascota pertenece a Úl.', max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_comment='Este campo almacena la fecha de nacimiento de la mascota. Es relevante para determinar la edad y estado de salud de la mascota, asÝ como para el seguimiento de su cuidado.', null=True)),
                ('especie', models.CharField(db_comment='Este campo almacena la especie de la mascota (por ejemplo, "Perro", "Gato"). Ayuda a clasificar las mascotas y gestionar su atenci¾n de acuerdo a su especie.', max_length=30)),
                ('raza', models.CharField(blank=True, db_comment='Este campo almacena la raza de la mascota (por ejemplo, "Labrador", "Siames"). Proporciona informaci¾n adicional que puede ser importante para el cuidado y tratamiento especÝfico de la mascota.', max_length=30, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascotas',
                'db_table_comment': 'La tabla MASCOTAS almacena informaci¾n sobre las mascotas de los clientes de la clÝnica veterinaria. Cada mascota tiene un identificador ·nico y se asocia con un cliente, permitiendo llevar un registro de las mascotas que son atendidas en la clÝnica.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosDePago',
            fields=[
                ('metodo_pago_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada mÚtodo de pago. Este valor debe ser ·nico y permite distinguir cada mÚtodo de manera clara.', primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(db_comment='Este campo almacena el tipo de pago (por ejemplo, "Tarjeta de crÚdito", "Tarjeta de dÚbito", "Transferencia bancaria"). Esto ayuda a clasificar los mÚtodos de pago disponibles.', max_length=20)),
                ('numero_tarjeta', models.CharField(db_comment='Este campo almacena el n·mero de la tarjeta de pago. Debe manejarse con cuidado y cumplir con las normativas de seguridad para proteger la informaci¾n sensible.', max_length=40)),
                ('nombre_titular', models.CharField(db_comment='Este campo almacena el nombre del titular de la tarjeta. Esto es importante para verificar que el mÚtodo de pago estÚ registrado correctamente a nombre del cliente.', max_length=40)),
                ('fecha_expiracion', models.DateField(db_comment='Este campo almacena la fecha de expiraci¾n de la tarjeta de pago. Es fundamental para asegurar que la tarjeta sea vßlida en el momento de realizar una transacci¾n.')),
                ('codigo_seguridad', models.CharField(db_comment='Este campo almacena el c¾digo de seguridad de la tarjeta (CVV). Es un elemento de seguridad adicional que se requiere al procesar pagos.', max_length=20)),
                ('estado', models.CharField(db_comment='Este campo almacena el estado del mÚtodo de pago (por ejemplo, "Activo", "Inactivo"). Esto permite gestionar quÚ mÚtodos de pago estßn disponibles para su uso.', max_length=20)),
            ],
            options={
                'db_table': 'metodos_de_pago',
                'db_table_comment': 'La tabla METODOS_DE_PAGO almacena informaci¾n sobre los diferentes mÚtodos de pago que los clientes pueden utilizar para realizar transacciones en la clÝnica veterinaria. Cada mÚtodo de pago tiene un identificador ·nico y puede incluir detalles sobre el cliente y la tarjeta de pago.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('notificacion_id', models.FloatField(db_comment='Este campo es la llave primaria de la tabla. Almacena un identificador ·nico para cada notificaci¾n. Este valor debe ser ·nico y permite distinguir cada notificaci¾n de manera clara.', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_comment='Este campo almacena el tipo de notificaci¾n (por ejemplo, "Recordatorio de cita", "Promoci¾n", "Actualizaci¾n de servicios"). Esto ayuda a categorizar las notificaciones y permite al cliente identificar rßpidamente la naturaleza de cada una.', max_length=20)),
                ('fecha_envio', models.DateField(blank=True, db_comment='Este campo es una llave forßnea que hace referencia a la cedula del cliente.', null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'db_table_comment': 'La tabla NOTIFICACIËN almacena informaci¾n sobre las notificaciones enviadas a los usuarios, generalmente clientes de la clÝnica veterinaria. Cada notificaci¾n tiene un identificador ·nico y puede incluir detalles como el usuario receptor, el tipo de notificaci¾n y la fecha en que fue enviada.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsddmwDiagrams',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('global_id', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('design_id', models.CharField(blank=True, max_length=70, null=True)),
                ('design_name', models.CharField(blank=True, max_length=256, null=True)),
                ('model_id', models.CharField(blank=True, max_length=70, null=True)),
                ('model_name', models.CharField(blank=True, max_length=256, null=True)),
                ('subview_id', models.CharField(blank=True, max_length=70, null=True)),
                ('subview_name', models.CharField(blank=True, max_length=256, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=70, null=True)),
                ('diagram_type', models.CharField(blank=True, max_length=10, null=True)),
                ('layout', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'osddmw_diagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.FloatField(db_comment='Este es el identificador ·nico del rol en la base de datos. Este campo es la clave primaria (PK) de la tabla, lo que significa que cada valor debe ser ·nico y no nulo.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre completo del rol. Por ejemplo, "Administrador", "Veterinario", "Usuario". Este campo es obligatorio y debe contener informaci¾n clara sobre la funci¾n o prop¾sito del rol.', max_length=50)),
                ('abreviacion', models.CharField(db_comment='Este campo guarda una versi¾n abreviada o un acr¾nimo del nombre del rol. Por ejemplo, "ADM" para "Administrador" o "VET" para "Veterinario". TambiÚn es un campo obligatorio y proporciona una forma rßpida de referirse al rol en sistemas o interfaces donde el espacio es limitado.', max_length=20)),
                ('descripcion', models.CharField(blank=True, db_comment='Este campo almacena una descripci¾n detallada del rol, explicando sus responsabilidades y funciones dentro del sistema. Es ·til para proporcionar mßs contexto sobre cada rol. Puede ser opcional o requerido, dependiendo de las necesidades del sistema.', max_length=100, null=True)),
            ],
            options={
                'db_table': 'roles',
                'db_table_comment': 'La tabla ROLES se utiliza para almacenar informaci¾n sobre los diferentes roles que pueden asignarse a los usuarios en el sistema. Cada rol define un conjunto de permisos y responsabilidades, lo que permite gestionar el acceso y las acciones que los usuarios pueden realizar dentro de la aplicaci¾n.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario', models.CharField(db_comment='Este campo es la llave primaria y almacena el nombre de usuario ·nico para cada usuario en el sistema. Debe ser ·nico y se utiliza para iniciar sesi¾n.', max_length=40, primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_comment='Este almacena el n·mero de cÚdula del usuario.', max_length=30)),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre del usuario. Es ·til para identificar al usuario dentro del sistema.', max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(db_comment='Este campo almacena la direcci¾n de correo electr¾nico del usuario. Debe ser ·nico, ya que se puede usar para recuperar contrase±as o enviar notificaciones.', max_length=30, unique=True)),
                ('clave', models.CharField(db_comment='Este campo almacena la contrase±a del usuario, que se utiliza para la autenticaci¾n al iniciar sesi¾n en el sistema.', max_length=128)),
                ('apellido2', models.CharField(blank=True, db_comment='Este campo almacena el apellido 1 del usuario. Es ·til para identificar al usuario dentro del sistema.', max_length=50, null=True)),
                ('apellido1', models.CharField(db_comment='Este campo almacena el apellido 1 del usuario. Es ·til para identificar al usuario dentro del sistema.', max_length=50)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'db_table_comment': 'La tabla USUARIOS almacena informaci¾n sobre los usuarios del sistema, que pueden ser veterinarios, administradores o due±os de clÝnicas. Cada usuario tiene un identificador ·nico y puede incluir detalles como cÚdula, nombre, telÚfono, correo electr¾nico, contrase±a, especialidad, clÝnica y rol.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitaServicios',
            fields=[
                ('cita', models.OneToOneField(db_comment='Este campo es la llave primaria y forßnea de la tabla. Almacena el identificador de la cita, haciendo referencia a la tabla CITAS. Permite vincular cada registro de servicio con la cita correspondiente.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Api.citas')),
            ],
            options={
                'db_table': 'cita_servicios',
                'db_table_comment': 'La tabla CITA_SERVICIOS almacena informaci¾n sobre los servicios especÝficos que se prestan durante cada cita en la clÝnica veterinaria. Esta tabla permite vincular citas con los servicios ofrecidos en esas citas, facilitando la gesti¾n y el seguimiento de la atenci¾n brindada.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaSintomas',
            fields=[
                ('sintoma', models.OneToOneField(db_comment='Este campo es una llave primaria y forßnea que almacena el identificador del sÝntoma. Hace referencia a la tabla SINTOMAS, permitiendo identificar quÚ sÝntoma se observ¾ o report¾ durante la consulta.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Api.sintomas')),
            ],
            options={
                'db_table': 'consulta_sintomas',
                'db_table_comment': 'La tabla CONSULTA_SINTOMAS almacena informaci¾n sobre los sÝntomas observados o reportados durante una consulta veterinaria. Cada registro en esta tabla vincula un sÝntoma especÝfico a una consulta, lo que permite hacer un seguimiento detallado de los sÝntomas asociados con cada mascota durante sus consultas.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaTratamientos',
            fields=[
                ('tratamiento', models.OneToOneField(db_comment='Este campo es una llave primaria y forßnea que almacena el identificador del tratamiento administrado. Hace referencia a la tabla TRATAMIENTOS, permitiendo identificar el tratamiento especÝfico que se ha realizado durante la consulta.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Api.tratamientos')),
            ],
            options={
                'db_table': 'consulta_tratamientos',
                'db_table_comment': 'La tabla CONSULTA_TRATAMIENTOS almacena informaci¾n sobre los tratamientos administrados durante las consultas a las mascotas. Cada registro vincula un tratamiento especÝfico a una consulta, permitiendo un seguimiento detallado de los tratamientos que se han realizado en cada consulta veterinaria.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaVacunas',
            fields=[
                ('vacuna', models.OneToOneField(db_comment='Este campo es una llave primaria y forßnea que almacena el identificador de la vacuna administrada. Hace referencia a la tabla VACUNAS, permitiendo identificar quÚ vacuna se administr¾ durante la consulta.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Api.vacunas')),
            ],
            options={
                'db_table': 'consulta_vacunas',
                'db_table_comment': 'La tabla CONSULTA_VACUNAS almacena informaci¾n sobre las vacunas que se administran durante las consultas veterinarias. Cada registro en esta tabla vincula una vacuna especÝfica a una consulta, lo que permite hacer un seguimiento detallado de las vacunas que se han aplicado a las mascotas en diferentes consultas.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('factura', models.OneToOneField(db_comment='Este campo es la llave primaria y forßnea de la tabla. Almacena el identificador de la factura asociada al pago, haciendo referencia a la tabla FACTURAS. Permite vincular cada pago con la factura correspondiente.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Api.facturas')),
                ('monto', models.FloatField(db_comment='Este campo almacena el monto que se pag¾. Es esencial para registrar la cantidad de dinero recibida por la clÝnica y para el control financiero.')),
            ],
            options={
                'db_table': 'pagos',
                'db_table_comment': 'La tabla PAGOS almacena informaci¾n sobre los pagos realizados por los clientes en relaci¾n con las facturas emitidas por los servicios de la clÝnica veterinaria. Esta tabla permite llevar un registro detallado de cada transacci¾n de pago, incluyendo el mÚtodo de pago utilizado y el monto pagado.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialServicios',
            fields=[
                ('servicio', models.OneToOneField(db_comment='Este campo es la llave primaria y forßnea de la tabla. Almacena el identificador del servicio prestado, haciendo referencia a la tabla SERVICIOS. Permite vincular el historial de servicios con el servicio especÝfico ofrecido.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Api.servicios')),
                ('fecha', models.DateField(db_comment='Este campo almacena la fecha en que se realiz¾ el servicio. Es importante para el seguimiento del historial de atenci¾n de la mascota y permite saber cußndo se brind¾ cada servicio.')),
                ('nombre', models.CharField(db_comment='Este campo almacena el nombre del servicio prestado en ese momento (por ejemplo, "Consulta Veterinaria"). Esto permite que el historial sea comprensible y claro para quienes lo revisen.', max_length=30)),
                ('descripcion', models.CharField(blank=True, db_comment='Este campo proporciona una descripci¾n detallada del servicio que se realiz¾. Ayuda a registrar informaci¾n especÝfica sobre la atenci¾n que recibi¾ la mascota en cada ocasi¾n.', max_length=50, null=True)),
                ('costo', models.FloatField(db_comment='Este campo almacena el costo del servicio que se prest¾. Es ·til para el seguimiento financiero y para que el cliente tenga un registro de los gastos asociados a los servicios brindados.')),
            ],
            options={
                'db_table': 'historial_servicios',
                'db_table_comment': 'La tabla HISTORIAL_SERVICIOS almacena informaci¾n sobre los servicios que han sido prestados a las mascotas a lo largo del tiempo. Esta tabla permite llevar un registro detallado de cada servicio realizado, junto con la fecha y otros detalles relevantes.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pesos',
            fields=[
                ('mascota', models.OneToOneField(db_comment='Este campo es la llave primaria y forßnea de la tabla. Almacena el identificador de la mascota cuyo peso se registra, haciendo referencia a la tabla MASCOTAS. Permite vincular cada registro de peso con la mascota correspondiente.', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Api.mascotas')),
                ('fecha', models.DateField(db_comment='Este campo almacena la fecha en que se registr¾ el peso. Aunque tÝpicamente se usarÝa un tipo de dato DATE, aquÝ se ha definido como VARCHAR. Es importante para rastrear cußndo se tomaron las mediciones de peso.')),
                ('peso', models.CharField(db_comment='Este campo almacena el peso de la mascota en la fecha especificada. Al ser un VARCHAR, es recomendable asegurarse de que los valores se ingresen en un formato consistente (por ejemplo, en kilogramos o libras).', max_length=20)),
            ],
            options={
                'db_table': 'pesos',
                'db_table_comment': 'La tabla PESOS almacena informaci¾n sobre el peso de las mascotas a lo largo del tiempo. Esta tabla permite llevar un registro del peso de cada mascota en diferentes fechas, lo cual es importante para el seguimiento de su salud y crecimiento.',
                'managed': False,
            },
        ),
    ]
