from .clients import *
from .clinics import *
from .pets import *
from .admin import *
from .vet import *
from .pet_record import *
from .vaccines import *
from .symptoms import *
from .treatments import *
from .appointments import *
from .schedules import *
from .services import *
from .clientPets import *
from .personalInfo import *
from .session import *
from .getRegisters import *
from .recover import *
from .payments import *
from .paymentMethods import *
from .paymentHistory import *
